[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cardiac-mri-cine-strain-engine"
version = "2.0.0"
description = "CardioMRI-Strain: Feature Tracking & Global Longitudinal Strain Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
cardiac-mri-cine-strain-engine = "cardio_mri_strain.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/cardiac-mri-cine-strain-engine"
Repository = "https://github.com/abusuraihsakhri/cardiac-mri-cine-strain-engine.git"
